# Generated by Django 3.1.1 on 2020-09-20 12:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lsp_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='peg_insert_date',
            field=models.DateField(blank=True, default=datetime.date(2020, 9, 20)),
        ),
        migrations.AlterField(
            model_name='patient',
            name='tt_due_date',
            field=models.DateField(blank=True, default=datetime.date(2020, 12, 13)),
        ),
        migrations.AlterField(
            model_name='patient',
            name='tt_insert_date',
            field=models.DateField(blank=True, default=datetime.date(2020, 9, 20)),
        ),
    ]
