# Generated by Django 3.1.1 on 2020-09-21 03:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lsp_app', '0002_auto_20200920_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='peg_insert_date',
            field=models.DateField(blank=True, default=datetime.date(2020, 9, 21)),
        ),
        migrations.AlterField(
            model_name='patient',
            name='tt_due_date',
            field=models.DateField(blank=True, default=datetime.date(2020, 12, 14)),
        ),
        migrations.AlterField(
            model_name='patient',
            name='tt_insert_date',
            field=models.DateField(blank=True, default=datetime.date(2020, 9, 21)),
        ),
    ]
