# Generated by Django 3.1.1 on 2020-09-27 08:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lsp_app', '0003_auto_20200921_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='peg_insert_date',
            field=models.DateField(blank=True, default=datetime.date(2020, 9, 27)),
        ),
        migrations.AlterField(
            model_name='patient',
            name='tt_due_date',
            field=models.DateField(blank=True, default=datetime.date(2020, 12, 20)),
        ),
        migrations.AlterField(
            model_name='patient',
            name='tt_insert_date',
            field=models.DateField(blank=True, default=datetime.date(2020, 9, 27)),
        ),
    ]
