# Generated by Django 3.1.1 on 2020-09-27 09:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lsp_app', '0004_auto_20200927_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='peg_due_date',
            field=models.DateField(blank=True, default=datetime.date(2021, 3, 14)),
        ),
    ]
