# Generated by Django 3.1.2 on 2020-10-28 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_name', models.CharField(default='DEFAULT VALUE', max_length=30)),
                ('insert_date', models.DateField()),
                ('type', models.CharField(blank=True, max_length=30, null=True)),
                ('size', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('due_date', models.DateField()),
                ('removal_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='DEFAULT VALUE', max_length=30)),
                ('mr_no', models.IntegerField()),
                ('tt_is_there', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(default='DEFAULT VALUE', max_length=30)),
                ('time', models.IntegerField()),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lsp_app.line')),
                ('patient', models.ManyToManyField(to='lsp_app.Patient')),
            ],
        ),
        migrations.AddField(
            model_name='line',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lsp_app.patient'),
        ),
    ]
