# Generated by Django 3.1.2 on 2020-10-31 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lsp_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='line',
        ),
        migrations.AddField(
            model_name='plan',
            name='line_name',
            field=models.CharField(default='DEFAULT VALUE', max_length=30),
        ),
        migrations.AlterField(
            model_name='line',
            name='line_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lsp_app.plan'),
        ),
    ]
